import { BookOpen, Code, Lightbulb, Headphones, Film, Globe } from "lucide-react"

export const availableIcons = [
  { id: "lightbulb", icon: <Lightbulb className="h-6 w-6 text-amber-500" />, name: "Lightbulb", color: "amber" },
  { id: "headphones", icon: <Headphones className="h-6 w-6 text-emerald-500" />, name: "Headphones", color: "emerald" },
  { id: "code", icon: <Code className="h-6 w-6 text-blue-500" />, name: "Code", color: "blue" },
  { id: "book", icon: <BookOpen className="h-6 w-6 text-purple-500" />, name: "Book", color: "purple" },
  { id: "film", icon: <Film className="h-6 w-6 text-rose-500" />, name: "Film", color: "rose" },
  { id: "globe", icon: <Globe className="h-6 w-6 text-teal-500" />, name: "Globe", color: "teal" },
]

export const getDefaultVideoCategories = () => [
  {
    id: "productivity-videos",
    name: "Productivity",
    icon: <Lightbulb className="h-6 w-6 text-amber-500" />,
    iconId: "lightbulb",
    description: "Boost your efficiency and get more done",
    videos: [
      {
        id: "prod-1",
        title: "Focus Toolkit",
        description: "Tools to Improve Your Focus by Andrew Huberman",
        videoUrl: "https://www.youtube.com/embed/yb5zpo5WDG4",
        isRecommended: true,
        duration: "1:51:31",
        thumbnail: "",
      },
      {
        id: "prod-2",
        title: "Motivation Explain by Dr. K",
        description: "What People Don't Get About Motivation",
        videoUrl: "https://www.youtube.com/watch?v=3QWIxElEnc8",
        duration: "33:23",
        thumbnail: "",
      },
      {
        id: "prod-3",
        title: "Task Batching",
        description: "Group similar tasks together for maximum efficiency",
        videoUrl: "https://www.youtube.com/watch?v=ua2L2Qf5cSY",
        duration: "12:45",
        thumbnail: "",
      },
    ],
  },
  {
    id: "meditation-videos",
    name: "Meditation",
    icon: <Headphones className="h-6 w-6 text-emerald-500" />,
    iconId: "headphones",
    description: "Find calm and improve mental clarity",
    videos: [
      {
        id: "med-1",
        title: "Introduction to Anapana",
        description: "Introduction to Anapana for All - Hindi by S.N. Goenka",
        videoUrl: "https://www.youtube.com/watch?v=byyz8FAvSsE",
        isRecommended: true,
        duration: "19:54",
        thumbnail: "",
      },
      {
        id: "med-2",
        title: "Anapana Meditation",
        description: "Anapana Meditation For All (Hindi - 10 mins)",
        videoUrl: "https://www.youtube.com/watch?v=mAtSIuTSx90",
        duration: "20:15",
        thumbnail: "",
      },
      {
        id: "med-3",
        title: "Vipassana Meditation",
        description: "Beginner level Vipassana Meditation",
        videoUrl: "https://www.youtube.com/watch?v=iBU3d-MTWsU",
        duration: "1:25:09",
        thumbnail: "",
      },
      {
        id: "med-4",
        title: "Vipassana Meditation",
        description: "Advance level Vipassana Meditation",
        videoUrl: "https://www.youtube.com/watch?v=gGbbSgD5jC0",
        duration: "1:18:35",
        thumbnail: "",
      },
    ],
  },
  {
    id: "nsdr-videos",
    name: "NSDR",
    icon: <Code className="h-6 w-6 text-blue-500" />,
    iconId: "code",
    description: "Rest properly with Non-Sleep Deep Rest",
    videos: [
      {
        id: "nsdr-1",
        title: "10 Minute NSDR",
        description: "Non-Sleep Deep Rest with Dr. Andrew Huberman",
        videoUrl: "https://www.youtube.com/watch?v=AKGrmY8OSHM",
        duration: "10:49",
        thumbnail: "",
      },
      {
        id: "nsdr-2",
        title: "15 minute Yoga Nidra",
        description: "15 minute Yoga Nidra",
        videoUrl: "https://www.youtube.com/watch?v=3bMP0NSwPgw&t=175s",
        isRecommended: true,
        duration: "32:15",
        thumbnail: "",
      },
      {
        id: "nsdr-3",
        title: "20 Minute Yoga Nidra",
        description: "Non-Sleep Deep Rest with Dr. Andrew Huberman",
        videoUrl: "https://www.youtube.com/watch?v=hEypv90GzDE",
        duration: "20:51",
        thumbnail: "",
      },
      {
        id: "nsdr-4",
        title: "30 minute NSDR",
        description: "Non-Sleep Deep Rest",
        videoUrl: "https://www.youtube.com/watch?v=6SdtKmXqkwc",
        duration: "30:00",
        thumbnail: "",
      },
    ],
  },
  {
    id: "study-videos",
    name: "Study With Me",
    icon: <BookOpen className="h-6 w-6 text-purple-500" />,
    iconId: "book",
    description: "Focus and study with virtual companions",
    videos: [
      {
        id: "study-1",
        title: "2-Hour Pomodoro Study Session",
        description: "Study session with timed breaks",
        videoUrl: "https://www.youtube.com/embed/382OExOIipQ",
        duration: "1:43:08",
        thumbnail: "",
      },
      {
        id: "study-2",
        title: "3-Hour Pomodoro Study Session",
        description: "Study session with timed breaks",
        videoUrl: "https://www.youtube.com/embed/ZMsTMuyH7w8",
        duration: "2:51:43",
        isRecommended: true,
        thumbnail: "",
      },
      {
        id: "study-3",
        title: "2-HOUR STUDY WITH ME",
        description: "Pomodoro timer 2x50 | Deep Focus | Lofi",
        videoUrl: "https://www.youtube.com/watch?v=QebXHPY7sac",
        duration: "2:00:00",
        thumbnail: "",
      },
    ],
  },
]

export const getDefaultWebsiteCategories = () => [
  {
    id: "productivity-websites",
    name: "Productivity",
    icon: <Lightbulb className="h-6 w-6 text-amber-500" />,
    iconId: "lightbulb",
    description: "Tools to boost your efficiency and get more done",
    websites: [
      {
        id: "prod-web-1",
        title: "Todoist",
        description: "Task management app that helps you stay organized",
        websiteUrl: "https://todoist.com",
        isRecommended: true,
        addedOn: "2023-05-15",
        favicon: "",
      },
      {
        id: "prod-web-2",
        title: "Notion",
        description: "All-in-one workspace for notes, tasks, wikis, and databases",
        websiteUrl: "https://notion.so",
        addedOn: "2023-06-20",
        favicon: "",
      },
      {
        id: "prod-web-3",
        title: "Trello",
        description: "Visual tool for organizing your work and life",
        websiteUrl: "https://trello.com",
        addedOn: "2023-07-10",
        favicon: "",
      },
    ],
  },
  {
    id: "meditation-websites",
    name: "Meditation",
    icon: <Headphones className="h-6 w-6 text-emerald-500" />,
    iconId: "headphones",
    description: "Resources for mindfulness and meditation",
    websites: [
      {
        id: "med-web-1",
        title: "Headspace",
        description: "Meditation and mindfulness app with guided sessions",
        websiteUrl: "https://www.headspace.com",
        isRecommended: true,
        addedOn: "2023-04-10",
        favicon: "",
      },
      {
        id: "med-web-2",
        title: "Calm",
        description: "App for sleep, meditation and relaxation",
        websiteUrl: "https://www.calm.com",
        addedOn: "2023-05-05",
        favicon: "",
      },
      {
        id: "med-web-3",
        title: "Insight Timer",
        description: "Free app with thousands of guided meditations",
        websiteUrl: "https://insighttimer.com",
        addedOn: "2023-06-15",
        favicon: "",
      },
    ],
  },
  {
    id: "learning-websites",
    name: "Learning",
    icon: <BookOpen className="h-6 w-6 text-purple-500" />,
    iconId: "book",
    description: "Educational resources and platforms",
    websites: [
      {
        id: "learn-web-1",
        title: "Khan Academy",
        description: "Free world-class education for anyone, anywhere",
        websiteUrl: "https://www.khanacademy.org",
        isRecommended: true,
        addedOn: "2023-03-25",
        favicon: "",
      },
      {
        id: "learn-web-2",
        title: "Coursera",
        description: "Online courses from top universities and companies",
        websiteUrl: "https://www.coursera.org",
        addedOn: "2023-04-18",
        favicon: "",
      },
      {
        id: "learn-web-3",
        title: "edX",
        description: "Free online courses from Harvard, MIT, and more",
        websiteUrl: "https://www.edx.org",
        addedOn: "2023-05-22",
        favicon: "",
      },
    ],
  },
  {
    id: "tools-websites",
    name: "Useful Tools",
    icon: <Code className="h-6 w-6 text-blue-500" />,
    iconId: "code",
    description: "Helpful online tools and utilities",
    websites: [
      {
        id: "tools-web-1",
        title: "Canva",
        description: "Graphic design platform for creating visual content",
        websiteUrl: "https://www.canva.com",
        isRecommended: true,
        addedOn: "2023-02-15",
        favicon: "",
      },
      {
        id: "tools-web-2",
        title: "Wolfram Alpha",
        description: "Computational intelligence for knowledge and answers",
        websiteUrl: "https://www.wolframalpha.com",
        addedOn: "2023-03-10",
        favicon: "",
      },
      {
        id: "tools-web-3",
        title: "Grammarly",
        description: "Digital writing assistant for clear, mistake-free writing",
        websiteUrl: "https://www.grammarly.com",
        addedOn: "2023-04-05",
        favicon: "",
      },
    ],
  },
]
